### ISSUE TITLE
Could not load completion data

### ISSUE THREAD

**Issue by statquant** [gaalcaras/ncm-R#11]
Hello, I am getting the following error when using ncm-R with vim 8.0.642 and latest nvim-r
`[ERROR] [ncm-R] Could not load completion data: 'ascii' codec can't decode byte 0xe2 in position 107: ordinal not in range(128)                                                                                                       
`
Would you have an idea ?

**Comment by gaalcaras** [comment]
Hi there,

Unfortunately, I had to put ncm-R on the back burner for a while, mainly because I had to switch from R to Python for work, so I rarely used ncm-R myself anymore. But I'm back at it now!

As you may know, ncm has been deprecated in favor of ncm2. Consequently, I won't be fixing any bug on the "old" version of ncm-R. You can try the [feature branch](https://github.com/gaalcaras/ncm-R/tree/ncm2) and see if your bug still happens.

**Comment by gaalcaras** [comment]
I have now merged the feature branch into `master`. I'm closing this issue since it's about an older version of ncm-R. Please feel free to **open a new issue** if you run into a similar bug with the latest version of ncm-R.
