### ISSUE TITLE
Can't get UltiSnips working

### ISSUE THREAD

**Issue by gregrs-uk** [gaalcaras/ncm-R#12]
I've installed the new version of ncm: [ncm2](https://github.com/ncm2/ncm2), UltiSnips and [ncm2-ultisnips](https://github.com/ncm2/ncm2-ultisnips). I have the following in my `init.vim`:

```
inoremap <silent> <expr> <CR> ncm2_ultisnips#expand_or("\<CR>", 'n')
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsEditSplit="vertical"
```

but I'm not seeing any snippet expansion. Is this because of the new version of ncm perhaps?

**Comment by gregrs-uk** [comment]
I've tried using the old version of ncm, which works okay, but ideally I guess it would be good to be able to use ncm2.

**Comment by gaalcaras** [comment]
Hi there,

Unfortunately, I had to put ncm-R on the back burner for a while, mainly because I had to switch from R to Python for work, so I rarely used ncm-R myself anymore.

The good news is, I temporarily had to work on a R project last week, and not having R completion with ncm2 was frustrating, so I've been working on updating ncm-R to make it work with ncm2.

I'm keeping it on a [feature branch](https://github.com/gaalcaras/ncm-R/tree/ncm2) for now. UltiSnips works for me, but you do have to configure it properly to work with ncm2 and ncm-R. Check out [this comment](https://github.com/ncm2/ncm2-ultisnips/issues/6#issuecomment-410186456) to make it work with `<Tab>`.

**Comment by gregrs-uk** [comment]
Many thanks @gaalcaras. I may not have time to test it immediately but when I do I'll give it a whirl…

**Comment by gaalcaras** [comment]
Awesome, keep me posted.

I have now merged the feature branch into `master`. Since this issue is about an older version of ncm, I'm now closing it. But feel free to **open a new issue** if you run into problems when setting up snippets.
