### ISSUE TITLE
ncm-R fails to load

### ISSUE THREAD

**Issue by sluedtke** [gaalcaras/ncm-R#3]
Hi there, 

I am getting the following error messages after starting nvim with an R file:
```
ERROR] ncm-R failed to load: 'NoneType' object has no attribute 'group'. 
```
Running on a KDE-neon user edition.

Do you have any idea.

**Comment by gaalcaras** [comment]
Thanks for the feedback.

Yes, I think I know where the bug comes from. I've pushed https://github.com/gaalcaras/ncm-R/commit/8b2e3fb8c985e82aa9ea33c526b101ff77e20a96 to `master`. Please update ncm-R and see if this fixes it.

If it's still not working, you may want to try the next version of ncm-R and Nvim-R by using the following branches (this is using `vim-plug`):

```
Plug 'jalvesaq/Nvim-R', { 'branch': 'auto_list' }
Plug 'gaalcaras/ncm-R', { 'branch': 'auto-list' }
```

If you still have the same bug at this point, I'll also need you to `cd` into `g:rplugin_compldir`, run `ls -l | grep omnils_` and give me the output.

**Comment by sluedtke** [comment]
Thanks for the fast reply .. 

I will try that before Christmas , but no promise at this point. 

either way, happy Christmas .. ;-)

**Comment by gaalcaras** [comment]
Update: ncm-R and Nvim-R have been updated, so you can stay on `master` and try their newest versions.

**Comment by sluedtke** [comment]
it looks good. The error at start up disappears and the package is working. 
thanks! I am looking forward to work with that.

**Comment by gaalcaras** [comment]
Awesome :) Don't hesitate to open a new issue if you find another bug or if you want to suggest a new feature.
