### ISSUE TITLE
Error "'\l' is an unrecognized escape sequence" when starting to type

### ISSUE THREAD

**Issue by oli666** [gaalcaras/ncm-R#4]
hi,
I get the attached error when starting to type the first letter in insert mode. 

![unbenannt](https://user-images.githubusercontent.com/7488029/34303861-a2f80fde-e737-11e7-869c-1c655ef8f89b.png)

Before that, I have successfully started R using <localLeader>rf and can send lines of code to the R process without issues. 
Also: the word completion works just fine and I have also used Jedi to test the python completen. All good on that front. 
Any glue what could cause the issue with the R completion? 
Thanks,
Oli

**Comment by gaalcaras** [comment]
Thanks for the feedback.

You have the exact same issue than: https://github.com/gaalcaras/ncm-R/issues/1#issuecomment-352434811

I know what's causing this bug on Windows 10. I think the next version of ncm-R will solve the issue, because it will interact with Nvim-R in a different way.

If you want to try the next version and see if it works, please use the following branches (this is using `vim-plug`):

```
Plug 'jalvesaq/Nvim-R', { 'branch': 'auto_list' }
Plug 'gaalcaras/ncm-R', { 'branch': 'auto-list' }
```

**Comment by oli666** [comment]
Good stuff! I have checked out the according branches and everything seems to be working now, excellent! Will start exploring this already awesome looking plug-in! Many thanks for the quick turn around. 
Oli

**Comment by gaalcaras** [comment]
That's great news!
 
Please note that I don't know when @javelsaaq or I will be merging the dev branches into `master`. But since they are feature branches, they'll probably be deleted in the near future so be on the lookout for that.

**Comment by jalvesaq** [comment]
I'm ready to merge the `auto_list` branch into `master`...

**Comment by gaalcaras** [comment]
It's ready for me too. Let's merge then :)

**Comment by jalvesaq** [comment]
Done!

**Comment by gaalcaras** [comment]
And... Done!
