### ISSUE TITLE
Very poor performance using vim8

### ISSUE THREAD

**Issue by statquant** [gaalcaras/ncm-R#5]
Hello, I have installed and setup a `vim8` version.
The completion appears to work but randomly makes vim freeze. Did you notice such occurrences ?
Is there any diagnostic tool I can use to test things up ?

I run `Fedora 26, vim 8.0.1360`, on a core i7, 16G RAM laptop (so should be plenty)

**Comment by gaalcaras** [comment]
Thanks for your feedback. I have not ran into this issue on my 7-year-old laptop or on my main machine with the same hardware config as yours (both running ArchLinux).

You're very welcome to try and debug this, since I can't reproduce it and I don't use vim8 as my daily editor. You can run `NVIM_PYTHON_LOG_FILE=nvim.log NVIM_PYTHON_LOG_LEVEL=INFO nvim` and look at `nvim.log_py3_cm_core`. You can also do `tail -f nvim.log_py3_cm_core | grep ncm-R` to get only ncm-R messages.

I think you should first determine if your performance issue is specific to vim by running ncm-R with Neovim and comparing performances. If the problem is specific to vim, then it's probably due to [NCM](https://github.com/roxma/nvim-completion-manager) and more specifically to the experimental [compatibility layer ](https://github.com/roxma/vim-hug-neovim-rpc). But I'm just guessing here ;-)
