### ISSUE TITLE
question about triggering autocompletion

### ISSUE THREAD

**Issue by cole-brokamp** [gaalcaras/ncm-R#7]
I'm enjoying ncm-R a lot, thank you very much for your work on this!  I can successfully get autocompletion working within a pipeline, e.g.

```r
library(tidyverse)
library(nycflights13)
data(flights)
flights %>%
    select(<CURSOR>
```

This finishes completion fine, but when I return to that code and want to change the word inside `select()`, the completion does not seem to work.  I've found that it only works when there is an open paren typed while in insert mode.  

In other words, is it possible to have the following code:

```r
flights %>%
    select(dep_delay)
```

and allow for autocompletion when changing the selected variable, i.e. `ciw` while the cursor is over `dep_delay`?

**Comment by cole-brokamp** [comment]
It's also a little unclear how I should be triggering autocompletion.  Am I right in assuming that this is taken care of by the usual vim autocompletion commands?  Sometimes autocompletion happens for me automatically as I type and sometime, I need to manually command it.  This could have something to do with other plugins (omnicomplete), though.

**Comment by gaalcaras** [comment]
Thanks a lot for your feedback.

> In other words, is it possible to [...] allow for autocompletion when changing the selected variable, i.e. ciw while the cursor is over dep_delay?

I've also noticed this. I think this might be a problem with [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager), since I also run into it with python completion:

```
import re
```

If I <kbd>ciw</kbd> on `re`, the pop-up menu doesn't come up. I have not looked into it too deeply, since it's not bothering me too much, but it's definitely on my list of things to tackle. In the meantime, you can maybe open an issue on [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager).

> It's also a little unclear how I should be triggering autocompletion

ncm-R is intended to provide "suggest as you type" completion, so in theory you should never need to trigger completion manually. Granted, the <kbd>ciw</kbd> is an unfortunate exception but it's the only one I can think of. If you do need to manually trigger completion, you should look into `:help <Plug>(cm_force_refresh)`. Note that if you ask for completion with omni-completion mapping (<kbd>\<C-o\></kbd>), you'll get Nvim-R omnicompletion instead.

**Comment by cole-brokamp** [comment]
Thank you for your helpful response.  This has cleared up a lot of confusion for me.  I did open an issue over at nvim-completion-manager

https://github.com/roxma/nvim-completion-manager/issues/173

I'll close now because this is an issue with the completion-manager and not R-specific.  I'll reopen if anything gets resolved.

Thanks again!
